server:
  port: 8080
spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  datasource:
    username: root
    password: zwz010929...
    # url->时区serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/nowcoder?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: top.chriszwz.community.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    top.chriszwz.community: debug

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test