server:
  port: 8080
#  servlet:
#    context-path: chris

spring:
  profiles:
    active: dev
  # thymeleaf 模板缓存关闭
  thymeleaf:
    cache: false

  # 数据库连接配置
  datasource:
    username: root
    password: 123456
    # url->时区serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/nowcoder?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # mail_properties
  mail:
    host: smtp.qq.com
    username: 2455781639@qq.com
    password: bxpxxzvyfruudiga
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          port: 465
# community
community:
  path:
    domain: http://localhost:8081

# mybatis配置
mybatis:
  type-aliases-package: top.chriszwz.community.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    use-generated-keys: true
#    map-underscore-to-camel-case: true # 驼峰命名
logging:
  level:
    top.chriszwz.community: debug

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test